---
name: Perl-Metrics-Simple
version: 0.021
author: []
abstract: 'Count packages, subs, lines, etc. of many files.'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  PPI: 1.113
  Pod::Usage: 0
  Readonly: 1.03
  Statistics::Basic: 0.42
build_requires:
  Module::Build: 0.2612
  Test::Pod: 1
  Test::Pod::Coverage: 1.04
provides:
  Perl::Metrics::Simple:
    file: lib/Perl/Metrics/Simple.pm
    version: 0.021
  Perl::Metrics::Simple::Analysis:
    file: lib/Perl/Metrics/Simple/Analysis.pm
    version: 0.021
  Perl::Metrics::Simple::Analysis::File:
    file: lib/Perl/Metrics/Simple/Analysis/File.pm
    version: 0.021
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
